# Generated by Django 4.2.27 on 2026-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_backfill_admin_profile_for_admin_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_base_url', models.CharField(blank=True, help_text='Public site URL, no trailing slash (e.g. https://crm.example.com). Used to show the webhook URL.', max_length=500)),
                ('verify_token', models.CharField(blank=True, help_text='Same token you enter in Meta Developer → Webhooks → Verify token.', max_length=255)),
                ('app_secret', models.CharField(blank=True, help_text='Meta App Secret (for X-Hub-Signature-256). Strongly recommended in production.', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='System User or permanent access token for sending WhatsApp replies via Graph API.')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, help_text='WhatsApp → API Setup → Phone number ID.', max_length=64)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('instagram_enabled', models.BooleanField(default=False)),
                ('notify_admins_on_message', models.BooleanField(default=True, help_text='Create an admin notification for each inbound WhatsApp/Instagram message.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta / WhatsApp / Instagram integration',
                'verbose_name_plural': 'Meta / WhatsApp / Instagram integration',
            },
        ),
    ]
