# Generated by Django 4.2.27 on 2026-03-30 05:48

from django.db import migrations, models


def enable_facebook_if_instagram_was_on(apps, schema_editor):
    """Keep prior behaviour: old single toggle also covered Page messaging."""
    MetaIntegrationSettings = apps.get_model("main_app", "MetaIntegrationSettings")
    for row in MetaIntegrationSettings.objects.all():
        if row.instagram_enabled:
            row.facebook_messenger_enabled = True
            row.save(update_fields=["facebook_messenger_enabled"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_meta_integration_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaintegrationsettings',
            options={'verbose_name': 'Meta / WhatsApp / Instagram / Facebook integration', 'verbose_name_plural': 'Meta / WhatsApp / Instagram / Facebook integration'},
        ),
        migrations.AddField(
            model_name='metaintegrationsettings',
            name='facebook_messenger_enabled',
            field=models.BooleanField(default=False, help_text='Inbound Facebook Page messages (Messenger) — webhook object type “page”.'),
        ),
        migrations.AlterField(
            model_name='metaintegrationsettings',
            name='notify_admins_on_message',
            field=models.BooleanField(default=True, help_text='Create an admin notification for each inbound WhatsApp / Instagram / Facebook message.'),
        ),
        migrations.RunPython(enable_facebook_if_instagram_was_on, noop_reverse),
    ]
