# Generated by Django 4.2.27 on 2026-03-30 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_facebook_messenger_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaintegrationsettings',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID for sending Messenger/Instagram replies (Graph API).', max_length=64),
        ),
        migrations.CreateModel(
            name='SocialChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], db_index=True, max_length=20)),
                ('external_user_id', models.CharField(db_index=True, help_text='WhatsApp wa_id or Messenger/Instagram scoped user id.', max_length=128)),
                ('page_or_waba_id', models.CharField(blank=True, help_text='Facebook Page id or WABA id from webhook entry (for routing sends).', max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_message_preview', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_threads', to='main_app.lead')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], db_index=True, max_length=3)),
                ('body', models.TextField()),
                ('external_message_id', models.CharField(blank=True, max_length=128)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main_app.socialchatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialchatthread',
            index=models.Index(fields=['channel', 'last_message_at'], name='main_app_so_channel_f9d283_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialchatthread',
            constraint=models.UniqueConstraint(fields=('channel', 'external_user_id', 'page_or_waba_id'), name='uniq_social_thread_channel_user_page'),
        ),
        migrations.AddIndex(
            model_name='socialchatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='main_app_so_thread__a7d00f_idx'),
        ),
    ]
